### PR TITLE
WIP : Around reactless

### PR DESCRIPTION
**Pull request by vinyll**
This is just a test to see how to compact the quantity and the spreading of the code.

Note that this is for testing purpose. I'm not sure we would go into this direction and it's very subject to reactions and opinions.

See [the appropriate commit](https://github.com/neomad-team/neomad.org/pull/102/commits/5bab044c93b352304c4e6e5267233d79ceea938d)

Note that we add 18 lines and remove 38. Meaning we cut half.

### CODE REVIEW

**Comment by fuentesloic** [comment]
I agree with you it's very understandable ! just one question: why remove you `Power` & `Rank` react components and not `Comments` ??
Because `Power` & `Rank` don't have an evolution "build" by JS right ? (I want say a component that not use map(), Math() or any other function)

**Review by fuentesloic — COMMENTED** [review]
I agree with you it's very understandable ! just one question: why remove you Power & Rank react components and not Comments ??
Because Power & Rank don't have an evolution "build" by JS right ? (I want say a component that not use `map()`, `fetch()`, `myFunction()` or any functions)

**Comment by vinyll** [comment]
I just didn't delete the "comment" because it was 2:30am and less straight forward, and this was just a trial ;)

**Comment by fuentesloic** [comment]
So ... if you delete `Comments` react component, you delete almost all the component, it's not a little weird ??

**Comment by vinyll** [comment]
check out the title of this PR: "reactless" ;)

**Comment by fuentesloic** [comment]
it's not false (that's work in english too ^^)

**Comment by fuentesloic** [comment]
I prefer this version, reactless is better (even if I will writte in react again - maybe - )
So what do you think about squashing and merging it ?

**Comment by vinyll** [comment]
Well, I'm not sure this is merge ready yet: it's still in React, but a bad React (because I broke the component you did like you should do).
Therefore I'd say either we go further on a road like this or we ditch this branch…

**Comment by fuentesloic** [comment]
If we stay on the `react` way, we write again and again new feature and we'll finish to keep react because that will be a huge job ... but in other way `react` (looking like cool) do the job and is a new thing but I'm still thinking like you, react oblige people to have knowledge in react (very few 'cause it's easy to learn). 
Using preact is better because that oblige me to keep my react simple (I can't use rooter for exemple).
So it's just a choice, for me, in this projet, even if I like react, we have to swicht for vanillaJS

**Comment by vinyll** [comment]
This may not be a good idea.
We'll reopen if ever.

**Pull request closed without merging**
