### PR TITLE
Reading time design

### PR DESCRIPTION
**Pull request by fuentesloic**

### CODE REVIEW

**Comment by fuentesloic** [comment]
Did: 
- modified date format (@vinyll with jinja it's so easy 👍 )
- Aligned reading time with the date
- Stole the medium design


Result:
capture d ecran 2017-06-26 a 10 00 22

I'm so professional in this picture !

AND yes I will squah all of them before merging :p

**Comment by newick** [comment]
your "desing" looks good for me! ;)

**Comment by vinyll** [comment]
I guess that's an implicit approval from @newick who didn't officially clicked _approved_ but still meaning you, @fuentesloic, can merge ;)

(I'm hoping you guys are not waiting for me to approve the approval :p )

**Review by newick — APPROVED** [review]

**Comment by newick** [comment]
damn I'm not used to it!

**Pull request merged**
