### PR TITLE
added location name for easy privacy locations editing

### PR DESCRIPTION
**Pull request by vinyll**
Guys, this is a mindblow! 🍸 

Users will have a list of city/country they visited for easier deletion!
I'm crazy about this as it means we're going to reuse this feature. To be continued 😈 

screen shot 2017-08-13 at 7 45 28 pm

### CODE REVIEW

**Comment by Ydrasil** [comment]
I don't know why circleci fail here, maybe try to rebuild it

**Comment by vinyll** [comment]
@Ydrasil: Still broken, even when reruning the tests

**Comment by Ydrasil** [comment]
I'll try to search where does issues come from.

**Comment by vinyll** [comment]
@Ydrasil: any clue so far? It would be great to get this merged.

**Comment by vinyll** [comment]
It seems that the template is using `user.current_location`. Maybe wrapping it with an `{% if %}` block as you did on another PR would do the trick

**Comment by fuentesloic** [comment]
nobody tried to wrap `user.current_location` ??

**Pull request merged**
