### PR TITLE
cleaned api spots migration and preparing new version of API

### PR DESCRIPTION
**Pull request by vinyll**

### CODE REVIEW

**Review by Ydrasil — APPROVED** [review]

**Comment by vinyll** [comment]
fixes #120

**Comment by vinyll** [comment]
@Ydrasil: I've added [this commit](https://github.com/neomad-team/neomad.org/pull/145/commits/ab21b42a5a8e6e11599868719adcae63c6e1025a) after your review.
Can you please revisit?

**Review by Ydrasil — APPROVED** [review]
What do you about instead of creating `data` from `spot.to_mongo()`, create data by hand for avoiding delete some fields like `del data[_id]`

**Comment by vinyll** [comment]
> What do you about instead of creating `data` from `spot.to_mongo()`, create data by hand for avoiding delete some fields like `del data[_id]`

That would be an option. However when using `to_mongo()`, any field that would be added to the model would automatically be present in the API too.
To be considered and discussed…

**Pull request merged**
