### PR TITLE
added slash on URLs ending

### PR DESCRIPTION
**Pull request by vinyll**
This makes all urls end with a `/`.
Flask automatically redirects a url that is missing a slash.

ie: `GET /login` makes a 302 to `/login/`

### CODE REVIEW

**Review by Ydrasil — COMMENTED** [review]
Why is there some css changes in this commit ?

**Comment by vinyll** [comment]
@Ydrasil: no good reason. It's fixed.

**Comment by fuentesloic** [comment]
you still have conflict

**Review by fuentesloic — APPROVED** [review]

**Comment by vinyll** [comment]
fixed conflicts

**Pull request merged**
