### PR TITLE
merge css

### PR DESCRIPTION
**Pull request by fuentesloic**

### CODE REVIEW

**Review by vinyll — APPROVED** [review]
I didn't test if it broke the rendering but I'll assume you have looked everything is still rendering fine.

I guess you could also take #79 and #78 in a next step so that you'll have completed a clean map 👍

**Comment by fuentesloic** [comment]
for now I will destruct this PR because I'm wondering about to have only one CSS ... I'm not sure it's a good idea or not

**Comment by vinyll** [comment]
I believe we should have a CSS that is shared at least for common styles (like the markers, popups and some other common items).
Eventually we'll end with some specific styles for each page that would go elsewhere.

**Comment by fuentesloic** [comment]
yes I wondering exactly the same !! So I open an issue for that I will do that after 'cause it's not really important now.
After features `around-rooterURL`  and `around-appPois` I will work on it

**Pull request closed without merging**
