### PR TITLE
Design

### PR DESCRIPTION
**Pull request by vinyll**
This is a partial redesign of the home page.

What changed:  alignment of the header and footer, sections "read and share", "track your trips" and "Find out…".

Sections Latest articles and below were not changed yet.

# Before

Screen Shot 2019-12-06 at 11 28 30-fullpage

# After

Screen Shot 2019-12-06 at 11 28 14-fullpage

### CODE REVIEW

**Comment by vinyll** [comment]
New proposal with alignments

Screen Shot 2019-12-06 at 11 57 56-fullpage

**Review by fuentesloic — DISMISSED** [review]
OH MY GOSH!!! 🎉 

Really nice improvemet

**Comment by newick** [comment]
nice idea to add illustrations! 
not very fond of the footer. Do we need the "read the source" link everywhere ? Maybe just a github link?
And the "signup to join them" was better before.

**Comment by vinyll** [comment]
@newick Footer is changed and button is fixed.

Screen Shot 2019-12-08 at 15 27 45

**Review by fuentesloic — APPROVED** [review]

**Pull request merged**
